apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - git:
        repoURL: https://github.com/tldms0327/argocd-dev.git
        revision: HEAD
        files:
          - path: "env/demo.yaml"

  template:
    metadata:
      name: "external-secrets"
      labels:
        app.kubernetes.io/instance: "addons"
  
    spec:
      project: addons
      destination:
        name: in-cluster
        namespace: addon-external-secrets
      source:
        repoURL: https://charts.external-secrets.io
        targetRevision: "0.5.8"
        chart: external-secrets
        helm:
          values: |-
            fullnameOverride: external-secrets
            serviceAccount:
              annotations:
                eks.amazonaws.com/role-arn: "arn:aws:iam::{{aws_account_id}}:role/irsa--{{cluster}}--external-secrets"
      ignoreDifferences:
        - kind: CustomResourceDefinition
          group: apiextensions.k8s.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig
        - kind: ValidatingWebhookConfiguration
          group: admissionregistration.k8s.io
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/1/clientConfig/caBundle

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true