apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-extra
spec:
  generators:
    - git:
        repoURL: https://github.com/tldms0327/argocd-dev.git
        revision: HEAD
        files:
          - path: "env/demo.yaml"

  template:
    metadata:
      name: "external-secrets-extra-{{cluster}}"
      labels:
        krmt.io/group: "addons"
    spec:
      project: addons
      destination:
        name: in-cluster
        namespace: addon-external-secrets-extra
      source:
        repoURL: https://charts.helm.sh/incubator
        targetRevision: "0.2.5"
        chart: raw
        helm:
          values: |-
            fullnameOverride: external-secrets-extra

            resources:
              - apiVersion: external-secrets.io/v1beta1
                kind: ClusterSecretStore
                metadata:
                  name: parameter-store
                spec:
                  provider:
                    aws:
                      region: ap-northeast-2
                      service: ParameterStore

              - apiVersion: external-secrets.io/v1beta1
                kind: ClusterSecretStore
                metadata:
                  name: secrets-manager
                spec:
                  provider:
                    aws:
                      region: ap-northeast-2
                      service: SecretsManager

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
