apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail
spec:
  generators:
    - git:
        repoURL: https://github.com/tldms0327/argocd-dev.git
        revision: HEAD
        files:
          - path: "env/demo.yaml"

  template:
    metadata:
      name: "promtail"
      labels:
        app.kubernetes.io/instance: "addons"
    spec:
      project: addons
      destination:
        name: in-cluster
        namespace: addon-promtail
      source:
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: "3.11.0"
        chart: promtail
        helm:
          values: |-
            fullnameOverride: promtail
            image:
              registry: docker.io
              repository: grafana/promtail
              tag: 2.1.0
            config:
              lokiAddress: https://loki.kkarin.com/loki/api/v1/push
              snippets:
                scrapeConfigs: |
                  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
                  - job_name: kubernetes-pods
                    pipeline_stages:
                      {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
                    kubernetes_sd_configs:
                      - role: pod
                    relabel_configs:
                      - source_labels:
                          - __meta_kubernetes_pod_controller_name
                        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                        action: replace
                        target_label: __tmp_controller_name
                      - source_labels:
                          - __meta_kubernetes_pod_label_app_kubernetes_io_name
                          - __meta_kubernetes_pod_label_app
                          - __tmp_controller_name
                          - __meta_kubernetes_pod_name
                        regex: ^;*([^;]+)(;.*)?$
                        action: replace
                        target_label: app
                      - source_labels:
                          - __meta_kubernetes_pod_label_app_kubernetes_io_component
                          - __meta_kubernetes_pod_label_component
                        regex: ^;*([^;]+)(;.*)?$
                        action: replace
                        target_label: component
              # snippets:
              #   extraClientConfigs: |
              #     external_labels:
              #       cluster: "{{cluster}}"
            # tolerations:
            #   - operator: Exists
          
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true