apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-server-2
resources:
- deployment.yaml
- service.yaml
# - secret.yaml

images:
- name: test-server-2
  newName: 400956673334.dkr.ecr.ap-northeast-2.amazonaws.com/test-server