---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-server
  namespace: argocd
  # annotations:
  #   recipients.argocd-notifications.argoproj.io: slack:noti-argocd
spec:
  project: app
  source:
    path: test-server
    repoURL: https://github.com/tldms0327/argocd-dev
    targetRevision: main
  destination:
    name: in-cluster
    namespace: test-server
  syncPolicy:
    syncOptions:
      - CreateNamespace=true