apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-delivery
  namespace: alert-delivery
  labels:
    app: alert-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-delivery
  template:
    metadata:
      labels:
        app: alert-delivery
    spec:
      serviceAccountName: alert-delivery
      containers:
        - name: alert-delivery
          image: alert-delivery
          resources:
            limits:
              cpu: "1024m"
              memory: 1Gi
            requests:
              cpu: "1024m"
              memory: 1Gi
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: client 
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /v1
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: http
              path: /v1
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: alert-delivery
            - secretRef:
                name: alert-delivery