apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: alert-delivery
spec:
  backendType: systemManager
  data: 
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_KR
      name: SLACK_WEBHOOK_URL_KR
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_LOG_KR
      name: SLACK_WEBHOOK_URL_LOG_KR
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_JP
      name: SLACK_WEBHOOK_URL_JP
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_LOG_JP
      name: SLACK_WEBHOOK_URL_LOG_JP
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_CA
      name: SLACK_WEBHOOK_URL_CA
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_LOG_CA
      name: SLACK_WEBHOOK_URL_LOG_CA
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_GB
      name: SLACK_WEBHOOK_URL_GB
    - key: /k8s/alpha/alert-delivery/alpha/SLACK_WEBHOOK_URL_LOG_GB
      name: SLACK_WEBHOOK_URL_LOG_GB
    - key: /k8s/alpha/alert-delivery/alpha/SENTRY_DSN
      name: SENTRY_DSN
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: Prune=false
        version: v1
