apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alert-delivery
resources:
- external-secrets.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- behavior: create
  envs:
  - configmap.config
  name: alert-delivery

images:
- name: alert-delivery
  newName: 400956673334.dkr.ecr.ap-northeast-2.amazonaws.com/alert-delivery

replicas:
- count: 1
  name: alert-delivery