apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alert-delivery
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: alert-delivery
  newName: 400956673334.dkr.ecr.ap-northeast-2.amazonaws.com/alert-delivery