apiVersion: v1
kind: Service
metadata:
  name: alert-delivery-http
spec:
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: alert-delivery
---
apiVersion: v1
kind: Service
metadata:
  name: alert-delivery-client
spec:
  ports:
    - name: client
      port: 3000
      targetPort: client
  selector:
    app: alert-delivery